"""
Django settings for hmc project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
# Env.read_env(os.path.join(BASE_DIR, 'hmc/.env')) #Taken out due to not being in django-environ quick start

# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(os.environ.get("DEBUG")) == "1"

ENV_ALLOWED_HOST = os.environ.get("ENV_ALLOWED_HOST")
ALLOWED_HOSTS = []
if ENV_ALLOWED_HOST:
    ALLOWED_HOSTS = [ENV_ALLOWED_HOST]

# SECURE_HSTS_SECONDS = os.environ.get("SECURE_HSTS_SECONDS")
# SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT") == "1"
# SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE") == "1"
# CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE") == "1"
# SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("SECURE_HSTS_INCLUDE_SUBDOMAINS") == "1"
# SECURE_HSTS_PRELOAD = os.environ.get("SECURE_HSTS_PRELOAD") == "1"
# SECURE_CROSS_ORIGIN_OPENER_POLICY = os.environ.get("SECURE_CROSS_ORIGIN_OPENER_POLICY")

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Apps
    "core",
    # "products",
    # "orders",
    # "invoice", #removed
    # AWS
    # "storages",
    # installed libraries
    # "django_browser_reload", #removed
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # installed libraries
    # installed libraries end
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hmc.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hmc.wsgi.application"


# Database

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Postgres database

POSTGRES_DB = os.environ.get("POSTGRES_DB")
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")
POSTGRES_USER = os.environ.get("POSTGRES_USER")
POSTGRES_HOST = os.environ.get("POSTGRES_HOST")
POSTGRES_PORT = os.environ.get("POSTGRES_PORT")
POSTGRES_ENGINE = os.environ.get("POSTGRES_ENGINE")

POSTGRES_IS_AVAIL = all([POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB, POSTGRES_HOST, POSTGRES_PORT])

# POSTGRES_READY = str(os.environ.get("POSTGRES_READY")) == "1"


# if POSTGRES_IS_AVAIL and POSTGRES_READY:

POSTGRES_IGNORE_SSL = os.environ.get("POSTGRES_IGNORE_SSL") == "true"

# if POSTGRES_IS_AVAIL and POSTGRES_READY:
if POSTGRES_IS_AVAIL:
    DATABASES = {
        "default": {
            "ENGINE": POSTGRES_ENGINE,
            "NAME": POSTGRES_DB,
            "USER": POSTGRES_USER,
            "PASSWORD": POSTGRES_PASSWORD,
            "HOST": POSTGRES_HOST,
            "PORT": POSTGRES_PORT,
        }
    }

    if not POSTGRES_IGNORE_SSL:
        DATABASES["default"]["OPTIONS"] = {"sslmode": "require"}  # type: ignore

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATIC_ROOT = BASE_DIR / "staticfiles-cdn"

STATICFILES_DIRS = [
    # BASE_DIR / "static",  #
    os.path.join(BASE_DIR, "static")
]

# from .cdn.conf import * # noqa

# from .cdn.conf import (
#         AWS_ACCESS_KEY_ID,
#         AWS_SECRET_ACCESS_KEY,
#         AWS_STORAGE_BUCKET_NAME,
#         AWS_S3_ENDPOINT_URL,
#         AWS_S3_OBJECT_PARAMETERS,
#         AWS_LOCATION,
#         DEFAULT_FILE_STORAGE,
#         STATICFILES_STORAGE,
#     )

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field


# ===================================================================
# This is to send emails from django project
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = os.environ.get("EMAIL_PORT")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_COMPANY = os.environ.get("EMAIL_HOST_COMPANY")
COMPANY_WEBSITE = os.environ.get("COMPANY_WEBSITE")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS")
# ===================================================================
# Client's portfolio link
PORTFOLIO_LINK = os.environ.get("PORTFOLIO_LINK")
# ===================================================================
