apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmc-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hmc-web-deployment
  template:
    metadata:
      labels:
        app: hmc-web-deployment
    spec:
      containers:
      - name: hmc
        image: registry.digitalocean.com/hmc/hmc-web:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: hmc-web-prod-env
        env:
          - name: PORT
            value: "8001"
        ports:
        - containerPort: 8001
      imagePullSecrets:
        - name: hmc

---
apiVersion: v1
kind: Service
metadata:
  name: hmc-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    app: hmc-web-deployment